[tools]
maven = "4.0.0-rc-5"

[tasks.reset]
run = [
    "nx run-many -t mvn-clean",
    "nx reset"
]

[tasks.build]
run = "nx run-many -t mvn-install"

[env]
_.path = ['{{config_root}}/node_modules/.bin']
